[project]
name = "UVFile"
version = "0.1.0"
description = "Like Brewfile but for UV"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "packaging",
]

[project.scripts]
uvfile = "uvfile.__main__:main"
